export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_SIGNUP_ERRORS = "USER_SIGNUP_ERRORS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_ERROR = "VERIFY_ERROR";
export const ACTIVATE_ERRORS = "ACTIVATE_ERRORS";
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const TRANSFER_SUCCESS = "TRANSFER_SUCCESS";
export const TRANSFER_ERROR = "TRANSFER_ERROR";
export const GET_TRANS_SUCCESS = "GET_TRANS_SUCCESS";
export const GET_TRANS_ERROR = "GET_TRANS_ERROR";
export const GET_USER_TRANS_SUCCESS = "GET_USER_TRANS_SUCCESS";
export const GET_USER_TRANS_ERROR = "GET_USER_TRANS_ERROR";
export const WITHDRAW_ERROR = "WITHDRAW_ERROR";







