export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_SIGNUP_ERRORS = "USER_SIGNUP_ERRORS";
export const ACTIVATE_SUCCESS = "ACTIVATE_SUCCESS";
export const ACTIVATE_ERRORS = "ACTIVATE_ERRORS";
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'SIGN_UP_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_SLOT_SUCCESS = 'GET_SLOT_SUCCESS';
export const GET_SLOT_ERROR = 'GET_SLOT_ERROR';
export const GET_ALL_WISHES_SUCCESS = 'GET_ALL_WISHES_SUCCESS';
export const GET_ALL_WISHES_ERROR = 'GET_ALL_WISHES_ERROR';
export const GET_ALL_PENDING_WISHES_SUCCESS = 'GET_ALL_PENDING_WISHES_SUCCESS';
export const GET_ALL_PENDING_WISHES_ERROR = 'GET_ALL_PENDING_WISHES_ERROR';
export const GET_ALL_FULFILLED_WISHES_SUCCESS = 'GET_ALL_FULFILLED_WISHES_SUCCESS';
export const GET_ALL_FULFILLED_WISHES_ERROR = 'GET_ALL_FULFILLED_WISHES_ERROR';




